name: 'BrowserStack Test'
on: [push, pull_request]
jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest  # Can be self-hosted runner also
    steps:

      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: 'Cypress Cucumber config'
          project-name: 'Cypress BDD v6.0'
          BUILD_ID: "f395555dd16f1dc5ee339e389186554911ded621"

      # The next 3 steps are for building the web application to be tested and starting the web server on the runner environment

      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: 'Install all npm dependencies'
        run: npm install
        
      - name: 'Run test'
        run: |
          echo "Calling the build status API.. fetching session id..."
          export BUILD_STATUS_RESPONSE=$( \
          curl -u "${{env.username}}:${{env.access-key}}" \
          -X GET "https://api-cloud.browserstack.com/app-automate/xcuitest/v2/builds/${{env.BUILD_ID}}" )
          npm run test   

